# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190330_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
